"""add_post_id_in_images_table

Revision ID: 0e8d22bdf102
Revises: 2daebf7e377c
Create Date: 2024-03-27 14:31:58.109171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8d22bdf102'
down_revision: Union[str, None] = '2daebf7e377c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'images', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('images', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'post_id')
    # ### end Alembic commands ###
