"""columms_rename

Revision ID: f3169d33e9ce
Revises: ff7e86a67da7
Create Date: 2024-03-25 10:22:41.762151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3169d33e9ce'
down_revision: Union[str, None] = 'cd87b20f6681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('images', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###
